//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeDirectory.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Employee
    {
        public int employeeID { get; set; }
        [Display(Name = "Location")]
        public int locationID { get; set; }
        public int roleID { get; set; }
        [Display(Name = "Title")]
        public int titleID { get; set; }
        [Display(Name = "Department")]
        public int departmentID { get; set; }
        [Display(Name = "Gender")]
        public string gender { get; set; }
        [Display(Name = "Street Address")]
        public string streetaddress { get; set; }
        [Display(Name = "City")]
        public string city { get; set; }
        [Display(Name = "State")]
        public string state { get; set; }
        [Display(Name = "Postal Code")]
        public string zipcode { get; set; }
        [Display(Name = "Country")]
        public string countryfull { get; set; }
        [Display(Name = "Email")]
        public string emailaddress { get; set; }
        [Display(Name = "Phone Number")]
        public string telephonenumber { get; set; }
        [Display(Name = "Birthday")]
        public string birthday { get; set; }
        [Display(Name = "First Name")]
        public string firstname { get; set; }
        [Display(Name = "Middle Initial")]
        public string middleinitial { get; set; }
        [Display(Name = "Last Name")]
        public string lastname { get; set; }
        public string imagelocation { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Location Location { get; set; }
        public virtual Title Title { get; set; }
    }
}
