//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeDirectory.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Employee
    {
        public int employeeID { get; set; }
        public int locationID { get; set; }
        public Nullable<int> roleID { get; set; }
        [Display(Name = "Title")]
        public int titleID { get; set; }
        [Display(Name = "Department")]
        public int departmentID { get; set; }
        [Display(Name = "Gender")]
        public string gender { get; set; }
        [Required(ErrorMessage = "Address is required")]
        [Display(Name = "Adress")]
        public string streetaddress { get; set; }
        [Required(ErrorMessage = "City is required")]
        [Display(Name = "City")]
        public string city { get; set; }
        [Required(ErrorMessage = "State is required")]
        [Display(Name = "State")]
        public string state { get; set; }
        [Required(ErrorMessage = "Postal Code is required")]
        [Display(Name = "Postal Code")]
        public string zipcode { get; set; }
        [Required(ErrorMessage = "Country is required")]
        [Display(Name = "Country")]
        public string countryfull { get; set; }
        [Required(ErrorMessage = "Email address is required")]
        [Display(Name = "Email")]
        public string emailaddress { get; set; }
        [Required(ErrorMessage = "Phone is required")]
        [Display(Name = "Phone")]
        public string telephonenumber { get; set; }
        [Required(ErrorMessage = "Birthday is required")]
        [Display(Name = "Birthday")]
        public string birthday { get; set; }
        [Required(ErrorMessage = "First name is required")]
        [Display(Name="First Name")]
        public string firstname { get; set; }
        [Display(Name = "Middle initial")]
        public string middleinitial { get; set; }
        [Required(ErrorMessage = "Last name is required")]
        [Display(Name = "Last Name")]
        public string lastname { get; set; }
        [Display(Name = "Image")]
        public string imagelocation { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Location Location { get; set; }
        public virtual Title Title { get; set; }
    }
}
