//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeDirectory.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public Location()
        {
            this.Employees = new HashSet<Employee>();
        }
    
        public int locationID { get; set; }
        public string locationname { get; set; }
        public string locationaddress { get; set; }
        public string locationcity { get; set; }
        public string locationzipcode { get; set; }
        public string locationState { get; set; }
        public string locationcountry { get; set; }
        public string locationphone { get; set; }
        public string locationweb { get; set; }
    
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
