//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeDirectory.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Title
    {
        public Title()
        {
            this.Employees = new HashSet<Employee>();
        }

        [Display(Name = "Title")]
        public int titleID { get; set; }
        [Display(Name = "Title")]
        public string titlename { get; set; }
    
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
